### ISSUE TITLE
Sporadic ValueError raised during `poetry install/sync` (with Poetry 2.x)

### ISSUE THREAD

**Issue by bcapitanu** [mtkennerly/poetry-dynamic-versioning#216]
Hello,

I initially thought that this is a Poetry bug, and started creating an issue on their issue tracker, but while getting all the required information, among which they asked for the output of `poetry -vvv <command-that-was-failing>`, I discovered in the resulting stack trace that this is caused by the `poetry-dynamic-versioning` plugin. 

You can read [this issue](https://github.com/python-poetry/poetry/issues/10090) for all the details, particularly the last section of the issue, titled `Poetry Runtime Logs`.

I've also changed my `pyproject.toml` to use the new way of invoking the plugin:
```
[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }
```
moving away from the `pipx inject poetry "poetry-dynamic-versioning[plugin]"`.

Since posting that issue on the Poetry tracker, I ran into it a few more times.  Here's one log output after changing to the `requires-plugins` configuration above:

```
[2025-01-21T22:51:16.942Z] py312: commands[0]> poetry -vvv sync --no-ansi --only=main,test
[2025-01-21T22:51:19.044Z] Adding repository PyPI (https://pypi.org/simple/) and setting it as primary
[2025-01-21T22:51:19.045Z] Adding repository asapp (https://pypi.infra.asapp.com/simple) and setting it as supplemental
[2025-01-21T22:51:19.360Z] Trying to detect current active python executable as specified in the config.
[2025-01-21T22:51:19.431Z] Found: /codefresh/volume/.tox_py312/py312/bin/python
[2025-01-21T22:51:19.560Z] Using virtualenv: /codefresh/volume/.tox_py312/py312
[2025-01-21T22:51:20.956Z] 
[2025-01-21T22:51:20.956Z]   Stack trace:
[2025-01-21T22:51:20.956Z] 
[2025-01-21T22:51:20.958Z]   12  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/application.py:327 in run
[2025-01-21T22:51:20.960Z]        325│ 
[2025-01-21T22:51:20.960Z]        326│             try:
[2025-01-21T22:51:20.960Z]      → 327│                 exit_code = self._run(io)
[2025-01-21T22:51:20.960Z]        328│             except BrokenPipeError:
[2025-01-21T22:51:20.960Z]        329│                 # If we are piped to another process, it may close early and send a
[2025-01-21T22:51:20.962Z] 
[2025-01-21T22:51:20.962Z]   11  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/poetry/console/application.py:236 in _run
[2025-01-21T22:51:20.967Z]        234│ 
[2025-01-21T22:51:20.967Z]        2****│         with directory(self._working_directory):
[2025-01-21T22:51:20.967Z]      → 236│             exit_code: int = super()._run(io)
[2025-01-21T22:51:20.967Z]        237│ 
[2025-01-21T22:51:20.967Z]        238│         return exit_code

[2025-01-21T22:51:21.033Z]   10  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/application.py:431 in _run
[2025-01-21T22:51:21.033Z]        429│             io.input.interactive(interactive)
[2025-01-21T22:51:21.033Z]        430│ 
[2025-01-21T22:51:21.034Z]      → 431│         exit_code = self._run_command(command, io)
[2025-01-21T22:51:21.034Z]        432│         self._running_command = None
[2025-01-21T22:51:21.034Z]        433│ 

[2025-01-21T22:51:21.042Z]    9  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/application.py:473 in _run_command
[2025-01-21T22:51:21.042Z]        471│ 
[2025-01-21T22:51:21.043Z]        472│         if error is not None:
[2025-01-21T22:51:21.044Z]      → 473│             raise error
[2025-01-21T22:51:21.044Z]        474│ 
[2025-01-21T22:51:21.044Z]        475│         return terminate_event.exit_code

[2025-01-21T22:51:21.058Z]    8  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/application.py:454 in _run_command
[2025-01-21T22:51:21.058Z]        452│ 
[2025-01-21T22:51:21.058Z]        453│         try:
[2025-01-21T22:51:21.058Z]      → 454│             self._event_dispatcher.dispatch(command_event, COMMAND)
[2025-01-21T22:51:21.058Z]        455│ 
[2025-01-21T22:51:21.136Z]        456│             if command_event.command_should_run():

[2025-01-21T22:51:21.137Z]    7  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/events/event_dispatcher.py:26 in dispatch
[2025-01-21T22:51:21.137Z]         24│ 
[2025-01-21T22:51:21.137Z]         25│         if listeners:
[2025-01-21T22:51:21.139Z]      →  26│             self._do_dispatch(listeners, event_name, event)
[2025-01-21T22:51:21.139Z]         27│ 
[2025-01-21T22:51:21.139Z]         28│         return event

[2025-01-21T22:51:21.153Z]    6  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/events/event_dispatcher.py:85 in _do_dispatch
[2025-01-21T22:51:21.153Z]         83│                 break
[2025-01-21T22:51:21.153Z]         84│ 
[2025-01-21T22:51:21.155Z]      →  85│             listener(event, event_name, self)
[2025-01-21T22:51:21.155Z]         86│ 
[2025-01-21T22:51:21.155Z]         87│     def _sort_listeners(self, event_name: str) -> None:

[2025-01-21T22:51:21.155Z]    5  .poetry/plugins/poetry_dynamic_versioning/plugin.py:182 in _apply_version

   4  .poetry/plugins/poetry_dynamic_versioning/plugin.py:84 in _apply_version_via_plugin

[2025-01-21T22:51:21.166Z]    3  .poetry/plugins/poetry_dynamic_versioning/__init__.py:699 in _get_and_apply_version

[2025-01-21T22:51:21.167Z]    2  .poetry/plugins/poetry_dynamic_versioning/__init__.py:597 in _apply_version

[2025-01-21T22:51:21.167Z]    1  <frozen _collections_abc>:1165 in remove

[2025-01-21T22:51:21.167Z]   ValueError

  

[2025-01-21T22:51:21.167Z]   at <frozen _collections_abc>:1063 in index
[2025-01-21T22:51:21.359Z] py312: exit 1 (4.62 seconds) /codefresh/volume/wuwei> poetry -vvv sync --no-ansi --only=main,test pid=2068
```

**Comment by bcapitanu** [comment]
This is not happening all the time... but happens often enough to be a problem.

**Comment by bcapitanu** [comment]
[This line](https://github.com/mtkennerly/poetry-dynamic-versioning/blob/7e60328c8d8eb72e7db201f7439de9309e3816ff/poetry_dynamic_versioning/__init__.py#L597) seems to be the one causing the exception

**Comment by bcapitanu** [comment]
I tested with latest release 1.7.0 and same issue occurs.

**Comment by mtkennerly** [comment]
Thanks for the detailed report! I don't understand why it only happens some of the time, but it seems like some kind of race condition and/or multiple execution issue. Anyway, it'll be easy enough to add a guard on that line to be safe :)

**Comment by bcapitanu** [comment]
Will you be releasing a `1.7.1` with this fix?  I'd be happy to test it 🚀

**Comment by mtkennerly** [comment]
Yep, I just published v1.7.1 now. Let me know how it goes!

**Comment by bcapitanu** [comment]
No joy, unfortunately.

I'm seeing some very strange errors.  

Run 1 (on Python 3.13 -- not sure if that's relevant):

```
[2025-01-23T04:25:36.125Z] lintcheck: commands[0]> poetry -vvv install --no-ansi --no-root --only=lint
[2025-01-23T04:25:38.198Z] 
[2025-01-23T04:25:38.204Z]   Stack trace:

[2025-01-23T04:25:38.204Z]   18  /codefresh/volume/.tox_py313/.tox/lib/python3.13/site-packages/cleo/application.py:327 in run
[2025-01-23T04:25:38.213Z]        325│ 
[2025-01-23T04:25:38.213Z]        326│             try:
[2025-01-23T04:25:38.213Z]      → 327│                 exit_code = self._run(io)
[2025-01-23T04:25:38.213Z]        328│             except BrokenPipeError:
[2025-01-23T04:25:38.213Z]        329│                 # If we are piped to another process, it may close early and send a

[2025-01-23T04:25:38.213Z]   17  /codefresh/volume/.tox_py313/.tox/lib/python3.13/site-packages/poetry/console/application.py:233 in _run
[2025-01-23T04:25:38.213Z]        231│         self._disable_cache = io.input.has_parameter_option("--no-cache")
[2025-01-23T04:25:38.213Z]        232│ 
[2025-01-23T04:25:38.213Z]      → 233│         self._load_plugins(io)
[2025-01-23T04:25:38.213Z]        234│ 
[2025-01-23T04:25:38.213Z]        2****│         with directory(self._working_directory):

[2025-01-23T04:25:38.227Z]   16  /codefresh/volume/.tox_py313/.tox/lib/python3.13/site-packages/poetry/console/application.py:399 in _load_plugins
[2025-01-23T04:25:38.227Z]        397│             PluginManager.add_project_plugin_path(self._project_directory)
[2025-01-23T04:25:38.227Z]        398│             manager = PluginManager(ApplicationPlugin.group)
[2025-01-23T04:25:38.227Z]      → 399│             manager.load_plugins()
[2025-01-23T04:25:38.227Z]        400│             manager.activate(self)
[2025-01-23T04:25:38.227Z]        401│ 

[2025-01-23T04:25:38.227Z]   15  /codefresh/volume/.tox_py313/.tox/lib/python3.13/site-packages/poetry/plugins/plugin_manager.py:75 in load_plugins
[2025-01-23T04:25:38.227Z]         73│ 
[2025-01-23T04:25:38.227Z]         74│         for ep in plugin_entrypoints:
[2025-01-23T04:25:38.227Z]      →  75│             self._load_plugin_entry_point(ep)
[2025-01-23T04:25:38.227Z]         76│ 
[2025-01-23T04:25:38.227Z]         77│     def get_plugin_entry_points(self) -> list[metadata.EntryPoint]:

[2025-01-23T04:25:38.227Z]   14  /codefresh/volume/.tox_py313/.tox/lib/python3.13/site-packages/poetry/plugins/plugin_manager.py:95 in _load_plugin_entry_point
[2025-01-23T04:25:38.227Z]         93│         logger.debug("Loading the %s plugin", ep.name)
[2025-01-23T04:25:38.295Z]         94│ 
[2025-01-23T04:25:38.295Z]      →  95│         plugin = ep.load()
[2025-01-23T04:25:38.295Z]         96│ 
[2025-01-23T04:25:38.295Z]         97│         if not issubclass(plugin, (Plugin, ApplicationPlugin)):

[2025-01-23T04:25:38.296Z]   13  /opt/.pyenv/versions/3.13.0/lib/python3.13/importlib/metadata/__init__.py:179 in load
[2025-01-23T04:25:38.296Z]         177│         """
[2025-01-23T04:25:38.306Z]         178│         match = cast(Match, self.pattern.match(self.value))
[2025-01-23T04:25:38.306Z]      →  179│         module = import_module(match.group('module'))
[2025-01-23T04:25:38.306Z]         180│         attrs = filter(None, (match.group('attr') or '').split('.'))
[2025-01-23T04:25:38.317Z]         181│         return functools.reduce(getattr, attrs, module)

[2025-01-23T04:25:38.317Z]   12  /opt/.pyenv/versions/3.13.0/lib/python3.13/importlib/__init__.py:88 in import_module
[2025-01-23T04:25:38.318Z]         86│                 break
[2025-01-23T04:25:38.318Z]         87│             level += 1
[2025-01-23T04:25:38.318Z]      →  88│     return _bootstrap._gcd_import(name[level:], package, level)
[2025-01-23T04:25:38.318Z]         89│ 
[2025-01-23T04:25:38.318Z]         90│ 

[2025-01-23T04:25:38.318Z]   11  <frozen importlib._bootstrap>:1387 in _gcd_import

[2025-01-23T04:25:38.318Z]   10  <frozen importlib._bootstrap>:1360 in _find_and_load

[2025-01-23T04:25:38.394Z]    9  <frozen importlib._bootstrap>:1310 in _find_and_load_unlocked

[2025-01-23T04:25:38.394Z]    8  <frozen importlib._bootstrap>:488 in _call_with_frames_removed
[2025-01-23T04:25:38.394Z] 
[2025-01-23T04:25:38.394Z]    7  <frozen importlib._bootstrap>:1387 in _gcd_import

[2025-01-23T04:25:38.399Z]    6  <frozen importlib._bootstrap>:1360 in _find_and_load

   5  <frozen importlib._bootstrap>:1331 in _find_and_load_unlocked

[2025-01-23T04:25:38.413Z]    4  <frozen importlib._bootstrap>:9**** in _load_unlocked

[2025-01-23T04:25:38.413Z]    3  <frozen importlib._bootstrap_external>:1022 in exec_module

[2025-01-23T04:25:38.413Z]    2  <frozen importlib._bootstrap>:488 in _call_with_frames_removed

[2025-01-23T04:25:38.426Z]    1  .poetry/plugins/poetry_dynamic_versioning/__init__.py:16 in <module>

[2025-01-23T04:25:38.426Z]   ModuleNotFoundError

[2025-01-23T04:25:38.426Z]   No module named 'jinja2.loaders'

[2025-01-23T04:25:38.426Z]   at .poetry/plugins/jinja2/__init__.py:18 in <module>
[2025-01-23T04:25:38.606Z] lintcheck: exit 1 (2.50 seconds) /codefresh/volume/wuwei> poetry -vvv install --no-ansi --no-root --only=lint pid=280
```

Run 2 (on Python 3.12):
```
[2025-01-23T04:25:56.709Z] py312: commands[0]> poetry -vvv sync --no-ansi --only=main,test
[2025-01-23T04:25:58.700Z] 
[2025-01-23T04:25:58.701Z]   Stack trace:
[2025-01-23T04:25:58.704Z] 
[2025-01-23T04:25:58.704Z]   17  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/cleo/application.py:327 in run
[2025-01-23T04:25:58.793Z]        325│ 
[2025-01-23T04:25:58.793Z]        326│             try:
[2025-01-23T04:25:58.793Z]      → 327│                 exit_code = self._run(io)
[2025-01-23T04:25:58.793Z]        328│             except BrokenPipeError:
[2025-01-23T04:25:58.793Z]        329│                 # If we are piped to another process, it may close early and send a

[2025-01-23T04:25:58.793Z]   16  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/poetry/console/application.py:233 in _run
[2025-01-23T04:25:58.804Z]        231│         self._disable_cache = io.input.has_parameter_option("--no-cache")
[2025-01-23T04:25:58.804Z]        232│ 
[2025-01-23T04:25:58.804Z]      → 233│         self._load_plugins(io)
[2025-01-23T04:25:58.804Z]        234│ 
[2025-01-23T04:25:58.804Z]        2****│         with directory(self._working_directory):

[2025-01-23T04:25:58.804Z]   15  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/poetry/console/application.py:399 in _load_plugins
[2025-01-23T04:25:58.808Z]        397│             PluginManager.add_project_plugin_path(self._project_directory)
[2025-01-23T04:25:58.808Z]        398│             manager = PluginManager(ApplicationPlugin.group)
[2025-01-23T04:25:58.808Z]      → 399│             manager.load_plugins()
[2025-01-23T04:25:58.808Z]        400│             manager.activate(self)
[2025-01-23T04:25:58.808Z]        401│ 

[2025-01-23T04:25:58.809Z]   14  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/poetry/plugins/plugin_manager.py:75 in load_plugins
[2025-01-23T04:25:58.809Z]         73│ 
[2025-01-23T04:25:58.809Z]         74│         for ep in plugin_entrypoints:
[2025-01-23T04:25:58.809Z]      →  75│             self._load_plugin_entry_point(ep)
[2025-01-23T04:25:58.820Z]         76│ 
[2025-01-23T04:25:58.820Z]         77│     def get_plugin_entry_points(self) -> list[metadata.EntryPoint]:

[2025-01-23T04:25:58.891Z]   13  /codefresh/volume/.tox_py312/.tox/lib/python3.12/site-packages/poetry/plugins/plugin_manager.py:95 in _load_plugin_entry_point
[2025-01-23T04:25:58.892Z]         93│         logger.debug("Loading the %s plugin", ep.name)
[2025-01-23T04:25:58.892Z]         94│ 
[2025-01-23T04:25:58.892Z]      →  95│         plugin = ep.load()
[2025-01-23T04:25:58.892Z]         96│ 
[2025-01-23T04:25:58.893Z]         97│         if not issubclass(plugin, (Plugin, ApplicationPlugin)):

[2025-01-23T04:25:58.893Z]   12  /opt/.pyenv/versions/3.12.7/lib/python3.12/importlib/metadata/__init__.py:205 in load
[2025-01-23T04:25:58.893Z]        203│         """
[2025-01-23T04:25:58.901Z]        204│         match = self.pattern.match(self.value)
     → 205│         module = import_module(match.group('module'))
[2025-01-23T04:25:58.905Z]        206│         attrs = filter(None, (match.group('attr') or '').split('.'))
[2025-01-23T04:25:58.905Z]        207│         return functools.reduce(getattr, attrs, module)

[2025-01-23T04:25:59.001Z]   11  /opt/.pyenv/versions/3.12.7/lib/python3.12/importlib/__init__.py:90 in import_module
[2025-01-23T04:25:59.001Z]         88│                 break
[2025-01-23T04:25:59.001Z]         89│             level += 1
[2025-01-23T04:25:59.002Z]      →  90│     return _bootstrap._gcd_import(name[level:], package, level)
[2025-01-23T04:25:59.002Z]         91│ 
[2025-01-23T04:25:59.002Z]         92│ 

[2025-01-23T04:25:59.002Z]   10  <frozen importlib._bootstrap>:1387 in _gcd_import
[2025-01-23T04:25:59.004Z] 
[2025-01-23T04:25:59.004Z]    9  <frozen importlib._bootstrap>:1360 in _find_and_load

[2025-01-23T04:25:59.004Z]    8  <frozen importlib._bootstrap>:1310 in _find_and_load_unlocked
[2025-01-23T04:25:59.004Z] 
[2025-01-23T04:25:59.004Z]    7  <frozen importlib._bootstrap>:488 in _call_with_frames_removed

[2025-01-23T04:25:59.004Z]    6  <frozen importlib._bootstrap>:1387 in _gcd_import

[2025-01-23T04:25:59.006Z]    5  <frozen importlib._bootstrap>:1360 in _find_and_load

[2025-01-23T04:25:59.006Z]    4  <frozen importlib._bootstrap>:1331 in _find_and_load_unlocked

[2025-01-23T04:25:59.008Z]    3  <frozen importlib._bootstrap>:9**** in _load_unlocked

[2025-01-23T04:25:59.008Z]    2  <frozen importlib._bootstrap_external>:995 in exec_module
[2025-01-23T04:25:59.008Z] 
[2025-01-23T04:25:59.009Z]    1  <frozen importlib._bootstrap>:488 in _call_with_frames_removed

[2025-01-23T04:25:59.009Z]   ModuleNotFoundError

[2025-01-23T04:25:59.009Z]   No module named 'dunamai'

[2025-01-23T04:25:59.009Z]   at .poetry/plugins/poetry_dynamic_versioning/__init__.py:19 in <module>
[2025-01-23T04:25:59.104Z] py312: exit 1 (2.70 seconds) /codefresh/volume/wuwei> poetry -vvv sync --no-ansi --only=main,test pid=2043
```

Run 3 (Python 3.12 -- removed verboseness)
```
[2025-01-23T04:32:24.828Z] py312: commands[0]> poetry sync --no-ansi --only=main,test
[2025-01-23T04:32:26.154Z] 
[2025-01-23T04:32:26.155Z] No module named 'jinja2.exceptions'
[2025-01-23T04:32:26.349Z] py312: exit 1 (1.58 seconds) /codefresh/volume/wuwei> poetry sync --no-ansi --only=main,test pid=443
```

Clearly there's some race condition, I think... 

Here's what a successful run looks like:

```
[2025-01-23T04:32:23.831Z] py311: commands[0]> poetry sync --no-ansi --only=main,test
[2025-01-23T04:32:26.137Z] Removing the project's plugin cache because it is outdated
[2025-01-23T04:32:26.142Z] Ensuring that the Poetry plugins required by the project are available...
[2025-01-23T04:32:26.358Z] The following Poetry plugins are required by the project but are not installed in Poetry's environment:
[2025-01-23T04:32:26.358Z]   - poetry-dynamic-versioning[plugin] (>=1.7.1,<2.0.0)
[2025-01-23T04:32:26.358Z] Installing Poetry plugins only for the current project...
[2025-01-23T04:32:26.360Z] Updating dependencies
[2025-01-23T04:32:26.431Z] Resolving dependencies...

[2025-01-23T04:32:30.038Z] Package operations: 4 installs, 0 updates, 0 removals

[2025-01-23T04:32:30.038Z]   - Installing markupsafe (3.0.2)
[2025-01-23T04:32:30.061Z]   - Installing dunamai (1.23.0)
[2025-01-23T04:32:30.061Z]   - Installing jinja2 (3.1.5)
[2025-01-23T04:32:30.071Z] Installing /codefresh/volume/.tox_py311/.tox/bin/dunamai over existing file
[2025-01-23T04:32:30.128Z]   - Installing poetry-dynamic-versioning (1.7.1)
[2025-01-23T04:32:30.133Z] Installing /codefresh/volume/.tox_py311/.tox/bin/poetry-dynamic-versioning over existing file
[2025-01-23T04:32:30.334Z] 
[2025-01-23T04:32:30.544Z] Writing lock file

[2025-01-23T04:32:30.544Z] Installing dependencies from lock file

[2025-01-23T04:32:31.429Z] Package operations: 81 installs, 0 updates, 1 removal

[2025-01-23T04:32:31.429Z]   - Removing wheel (0.45.1)
[2025-01-23T04:32:32.580Z]   - Installing nvidia-nvjitlink-cu12 (12.4.127)
[2025-01-23T04:32:33.862Z]   - Installing filelock (3.16.1)
[2025-01-23T04:32:33.862Z]   - Installing frozenlist (1.5.0)
[2025-01-23T04:32:33.863Z]   - Installing idna (3.10)
[2025-01-23T04:32:33.863Z]   - Installing markupsafe (3.0.2)
[2025-01-23T04:32:33.868Z]   - Installing mpmath (1.3.0)
[2025-01-23T04:32:33.869Z]   - Installing multidict (6.1.0)
[2025-01-23T04:32:33.872Z]   - Installing nvidia-cublas-cu12 (12.4.5.8)
[2025-01-23T04:32:33.929Z]   - Installing nvidia-cusparse-cu12 (12.3.1.170)
[... snip ...]
```

The sporadic nature of the error is still there.... some parallel jobs complete successfully, while others fail as shown above.

**Comment by mtkennerly** [comment]
Hmm, those are all import errors:

```
[2025-01-23T04:25:38.426Z]   No module named 'jinja2.loaders'
[2025-01-23T04:25:59.009Z]   No module named 'dunamai'
[2025-01-23T04:32:26.155Z] No module named 'jinja2.exceptions'
```

It's been a while since I used Tox, so I'm not sure what to check specifically, but it seems like some kind of problem in the Tox setup.

With `requires-plugins`, Poetry installs the plugin in `./.poetry`. Are the Tox instances all using that same folder, perhaps in parallel?

**Comment by bcapitanu** [comment]
No - all `tox` instances use different folders.... you can see in the logs above:

```
/codefresh/volume/.tox_py313/.tox/
/codefresh/volume/.tox_py312/.tox/
/codefresh/volume/.tox_py311/.tox/
```

I can try reverting to the old way of installing `poetry-dynamic-versioning` plugin and see if it makes a difference.

**Comment by bcapitanu** [comment]
Here's an example of the project config and tox config I use in `pyproject.toml`

```
[project]
name = "wuwei"
dynamic = ["version"]
requires-python = ">=3.10,<4"
dependencies = [
    "pytorch-lightning (>=2.0.0,<3.0.0)",
    "mlflow-skinny (>=2.0.0,<3.0.0)"
]

[tool.poetry]
requires-poetry = ">=2.0.1"
packages = [
    { include = "wuwei" },
]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.7.1,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = '''
(?x)                                                            (?# ignore whitespace)
    ^v?((?P<epoch>\d+)!)?(?P<base>\d+(\.\d+)*)                  (?# [v]1.2.3 or [v]1!2000.1.2)
    ([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\d+)?))?     (?# b0)
    (\+(?P<tagged_metadata>.+))?$                               (?# +linux)
'''

[tool.poetry.group.lint.dependencies]
ruff = "^0.9.0"

[tool.tox]
legacy_tox_ini = """
[tox]
min_version = 4.0
envlist =
    lintcheck
    py{310,311,312,313}
skipsdist = true
requires =
    poetry == 2.0.1

[testenv]
description = run unit tests
setenv =
    COVERAGE_FILE=.coverage.{envname}
allowlist_externals =
    mkdir
    poetry
commands =
    poetry -vvv sync --no-ansi --only=main,test
   
[testenv:lintcheck]
description = run lint checks
allowlist_externals = poetry
commands =
    poetry -vvv install --no-ansi --no-root --only=lint
"""
```

**Comment by bcapitanu** [comment]
I'm beginning to believe the that problem is indeed on the Poetry side, having to do with plugin installation.

**Comment by bcapitanu** [comment]
Your observations seem to support the hypothesis that Poetry doesn't play well with parallel invocations when plugins are concerned. Poetry seems to be maintaining some global state that gets corrupted by parallel invocations due to race conditions , overwrites, or other issues.

**Comment by bcapitanu** [comment]
Thanks so much for your help, @mtkennerly ! 🙏

**Comment by mtkennerly** [comment]
No problem \:D
